create table if not exists b2b_sales_tracker (
  id uuid default gen_random_uuid() primary key,
  airtable_record_id text unique not null,
  lead_name text,
  company_name text,
  owner_role text,
  email text,
  phone text,
  city text,
  country text,
  annual_rev text,
  website text,
  date_booked timestamptz,
  appointment_date date,
  show_status text,
  qualified text,
  lead_quality_score integer,
  call_outcome text,
  deposit boolean default false,
  cash_collected numeric,
  contract_value numeric,
  offer text,
  notes text,
  objection text,
  closer text,
  set_type text,
  ad_name text,
  ad_set_name text,
  campaign_name text,
  month_key text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
